Repository dev-laky/PeakPoker, pull requests merged in 2025-06, with the labels that each got.

#59 feat: add Dokka Maven plugin for documentation generation
  pom.xml
Labels: documentation, enhancement

#62 refactor(hand): adjustment for oop style improvements
  src/main/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluator.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/hand/PokerHand.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluatorTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/hand/PokerHandTest.kt
Labels: refactor/fix

#64 feat(poker-round): implement side pot logic and winnings distribution
  pom.xml
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/CommunityCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/Game.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/PokerGame.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluator.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/PokerPlayer.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/pot/PokerPots.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/pot/Pot.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/round/PokerRound.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluatorTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/pot/PokerPotsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/pot/PotTest.kt
Labels: enhancement

#67 feat(round): provide tests for `PokerRound` + adjust minor concerns
  pom.xml
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/CreateNewGame.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRound.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/cards/CommunityCardsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/deck/DeckTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/GameTestCustomPlayers.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRoundBettingTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRoundCallbackTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRoundGamePhaseTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRoundInfoTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRoundPlayerStateResetTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRoundResetingTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRoundSpecificPlayerTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluatorTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/hand/PokerHandTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/pot/PokerPotsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/pot/PotTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/persistence/FileSystemPersistenceAdapterTest.kt
Labels: enhancement

#69 chore(format): apply formatter
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/CommunityCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/HoleCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/Rank.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/Suit.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/deck/Deck.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/PokerGame.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/PokerRound.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluator.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/PokerPlayer.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/pot/PokerPots.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/pot/Pot.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/pot/PotInfo.kt
Labels: refactor/fix
