Repository dev-laky/PeakPoker, pull requests merged in 2025-05, with the labels that each got.

#19 feat: hand evaluation
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/HandEvaluator.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/HandEvaluatorTest.kt
Labels: enhancement, help wanted

#21 update: changes of consultation 1
  LICENSE
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/Card.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/deck/Deck.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/GameAction.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/GameState.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/HandEvaluator.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/Player.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/PlayerRole.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/entities/BetEntity.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/entities/GameEntity.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/entities/GamePlayerEntity.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/tables/Bets.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/tables/GamePlayers.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/tables/Games.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/DeckTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/HandEvaluatorTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/PlayerTest.kt
Labels: enhancement

#28 refactor: remove/queue db implementation
  pom.xml
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/db/DbConnect.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/db/DbInit.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/ConnectionHandler.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/config/DatabaseConfig.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/entities/BetEntity.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/entities/DeckEntity.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/entities/GameEntity.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/entities/GamePlayerEntity.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/entities/PlayerEntity.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/tables/Bets.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/tables/Decks.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/tables/GamePlayers.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/tables/Games.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/db/tables/Players.kt
Labels: refactor/fix

#29 feat(test): additional tests for hand eval
  src/test/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluatorTest.kt
Labels: enhancement

#30 feat(tests): add a test for the main function
  src/main/kotlin/hwr/oop/projects/peakpoker/Main.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/MainTest.kt
Labels: enhancement

#20 feat: implement Game class with player management and basic game func…
  src/main/kotlin/hwr/oop/projects/peakpoker/Main.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/Game.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/Player.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/GameTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/player/PlayerTest.kt
Labels: enhancement

#34 chore(build): build/exec game on WIN OS
  poker.cmd
  poker.ps1
Labels: enhancement

#31 feat: added `HoleCard` and `CommunityCard` types
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/CommunityCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/HoleCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/Game.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/GameInterface.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluator.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/hand/HandRank.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/Player.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/PlayerInterface.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/cards/CommunityCardsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/cards/HoleCardsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/GameTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluatorTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/player/PlayerTest.kt
Labels: enhancement

#47 feat/refactor(game): `GameId` data class added + `formatting.xml` + refactored game tests
  src/main/kotlin/hwr/oop/projects/peakpoker/Main.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/PokerCommand.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/db/DbCommand.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/db/DbConnect.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/db/DbInit.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/game/GameCommand.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/game/GameNew.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/hand/HandCommand.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/CommunityCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/HoleCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/Rank.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/Suit.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/deck/Deck.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/Game.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/GameAction.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/GameId.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/GameInterface.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/GameState.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluator.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/hand/HandRank.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/Player.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/PlayerInterface.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/PlayerRole.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/MainTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/commands/DbCommandTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/commands/DbConnectTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/commands/DbInitTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/commands/PokerTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/cards/CommunityCardsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/cards/HoleCardsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/deck/DeckTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/GameTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/GameTestCustomPlayers.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/GameTestThreePlayers.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/hand/HandEvaluatorTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/player/PlayerTest.kt
Labels: enhancement

#49 feat: add custom exceptions for betting, card, game state, and player…
  src/main/kotlin/hwr/oop/projects/peakpoker/commands/game/GameNew.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/CommunityCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/card/HoleCards.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/deck/Deck.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/exceptions/BettingException.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/exceptions/CardException.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/exceptions/DeckException.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/exceptions/GameException.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/exceptions/GameStateException.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/exceptions/PlayerException.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/game/Game.kt
  src/main/kotlin/hwr/oop/projects/peakpoker/core/player/Player.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/cards/CommunityCardsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/cards/HoleCardsTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/deck/DeckTest.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/GameTestCustomPlayers.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/game/GameTestThreePlayers.kt
  src/test/kotlin/hwr/oop/projects/peakpoker/core/player/PlayerTest.kt
Labels: enhancement
